### ISSUE TITLE
Lenovo Z400 running the same processor.

### ISSUE THREAD

**Issue by msamoeed** [osx86-ijb/Dell-Latitude-e5430-3rd-Gen-Core-i5-3210m-macOS-BigSur#2]
I used your EFI and i get this error ALPS DRIVER: TouchPad did not match any known IDS. Any ideas what i need to change to make it work on my machine.

Under that it gets stuck at 
apfs_module_start : 1683

**Comment by osx86-ijb** [comment]
No because that machines hardware is different, and this is set up for that
specific machine’s hardware.

**Comment by osx86-ijb** [comment]
No because this EFI is not made for that machine nor is that machines hardware the same as this one. It's advised that you don't attempt to just use a different EFI just because it has the same processor. That's not how things work. Follow the Dortania guide and do what it says as it walks through the entire process. 

> I used your EFI and i get this error ALPS DRIVER: TouchPad did not match any known IDS. Any ideas what i need to change to make it work on my machine.
> 
> 
> 
> Under that it gets stuck at 
> 
> apfs_module_start : 1683
